url: http://www.princetonindex.co
baseurl:

# Site settings
title: PRINCETON
subtitle: index
email: princetonindex@gmail.com
description: "PRINCETON Index"
copyright_year: 2015

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: f78f1e
  secondary: fec503
  secondary-dark: 333

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/princetonindex
  - title: github
    url: http://github.com/princetonindex
  - title: linkedin
    url: https://www.linkedin.com/grp/home?gid=6992726

contact:
  - icon: envelope
    url: mailto:princetonindex@gmail.com

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty