url: http://www.princetonindex.co
baseurl:

# Site settings
title: Princeton
subtitle: index
email: info@princetonindex.co
description: "Princeton Index."
copyright_year: 2015

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: f78f1e
  secondary: fec503
  secondary-dark: 333

# Team names, titles and social links
people:
- name: "Prin Ceton, '02"
  pic: default-headshot
  # position: Lead Designer
  social:
    - title: twitter
      url: http://www.twitter.com/foobar
    - title: linkedin
      url: http://www.linkedin/foobar

- name: "Prin Ceton, '02"
  pic: default-headshot
  # position: Lead Marketer
  social:
    - title: twitter
      url: http://www.twitter.com/foobar
    - title: linkedin
      url: http://www.linkedin/foobar

- name: "Prin Ceton, '02"
  pic: default-headshot
  # position: Lead Developer
  social:
    - title: linkedin
      url: http://www.linkedin/foobar

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/princetonindex
  - title: github
    url: http://github.com/princetonindex

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty